package br.com.senac.sistemapagamento.views;

import br.com.senac.sistemapagamento.dao.LoginDAO;
import br.com.senac.sistemapagamento.models.Criptografia;
import br.com.senac.sistemapagamento.models.Login;
import javax.swing.JOptionPane;

/**
 * Tela de login do sistema de cadastro de pagamento (SCP). Permite que o
 * usuário insira suas credenciais para acessar o sistema.
 *
 * @author alanm
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Construtor que inicializa os componentes da interface gráfica e define o
     * título da janela.
     */
    public TelaLogin() {
        initComponents(); // Inicializa os componentes da interface gráfica
        setTitle("Sistema de cadastro de Pagamento - SCP"); // Define o título da janela
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        cbxEsqueciSenha = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sistema de Cadastro de Pagamentos - SCP"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Sing in");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 87, -1));

        jLabel2.setText("Usuário:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 58, -1));

        txtLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtLogin.setText("Informe seu usuáro ex: nome@nome");
        jPanel1.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, 38));

        jLabel3.setText("Senha:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 47, -1));
        jPanel1.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 213, 38));

        btnEntrar.setBackground(new java.awt.Color(0, 51, 204));
        btnEntrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("ENTRAR");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 152, 33));

        cbxEsqueciSenha.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        cbxEsqueciSenha.setText("Esqueci minha senha");
        cbxEsqueciSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEsqueciSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(cbxEsqueciSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ação executada ao clicar no botão "Entrar". Valida as credenciais
     * informadas e redireciona o usuário para a tela inicial se o login for
     * bem-sucedido.
     */
    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed

        // Cria um novo objeto de login e define os dados informados pelo usuário
        Login login = new Login();
        login.setLogin(txtLogin.getText()); // Captura o nome de usuário informado

        // Criptografa a senha informada utilizando o algoritmo MD5
        String senhaCriptografada = Criptografia.getMD5(txtSenha.getText());
        login.setSenha(senhaCriptografada); // Define a senha criptografada no objeto login

        // Chama o método que valida o usuário no banco de dados
        login = LoginDAO.validarUsuario(login);

        if (login != null) {
            // Caso as credenciais sejam válidas, a tela incial abrirá
            TelaInicial telaInicial = new TelaInicial();
            telaInicial.setVisible(true); // Torna a tela inicial visível
            this.dispose();// Fecha a tela de login
        } else {
            // Exibe uma mensagem de erro caso as credenciais sejam inválidas
            JOptionPane.showMessageDialog(null, "Erro de autenticação! Verifique se os dados estão corretos.");
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * Ação executada ao clicar na opção "Esqueci minha senha". Abre a tela de
     * recuperação de senha.
     */
    private void cbxEsqueciSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEsqueciSenhaActionPerformed
        TelaRecuperar telaRecuperar = new TelaRecuperar(); // Cria uma nova instância da tela de recuperação
        telaRecuperar.setVisible(true); // Torna a tela de recuperação visível
    }//GEN-LAST:event_cbxEsqueciSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JCheckBox cbxEsqueciSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
