package br.com.senac.sistemapagamento.views;

import br.com.senac.sistemapagamento.dao.DadosBancarioDAO;
import br.com.senac.sistemapagamento.dao.EmpresaDAO;
import br.com.senac.sistemapagamento.models.DadosBancario;
import br.com.senac.sistemapagamento.models.Empresa;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Tela de exibição e manipulação de empresas e seus dados bancários.
 * 
 * @author alanm
 */
public class TelaEmpresa extends javax.swing.JFrame {

    // Método responsável por preencher a tabela de empresas e seus dados bancários
    public void preencherTabela(List<Empresa> empresa) {
        String colunas[] = {
            "ID", "CNPJ", "Nome Empresa", "Nome Banco",
            "Código Banco", "Tipo Conta", "Agência",
            "Dígito Agência", "Conta", "Dígito Conta",
            "Chave Pix", "CNPJ Recebedor", "Nome Recebedor"
        };

        // Calcula o número total de linhas necessárias para exibir os dados bancários
        int totalLinhas = 0;
        for (Empresa e : empresa) {
            totalLinhas += e.getDadosBancarios().size();
        }

         // Matriz que armazenará os dados para serem exibidos na tabela
        String dados[][] = new String[totalLinhas][colunas.length];
        int i = 0;
        for (Empresa e : empresa) {
            for (DadosBancario db : e.getDadosBancarios()) {
                dados[i] = new String[]{
                    String.valueOf(e.getId()),
                    e.getCnpj(),
                    e.getNomeEmpresa(),
                    db.getNome_banco(),
                    String.valueOf(db.getCodigo_banco()),
                    db.getTipo_conta(),
                    String.valueOf(db.getAgencia()),
                    String.valueOf(db.getDigito_agencia()),
                    String.valueOf(db.getConta()),
                    String.valueOf(db.getDigito_conta()),
                    db.getChave_pix(),
                    db.getCnpj_recebedor(),
                    db.getNome_recebedor()
                };
                i++;
            }
        }

         // Preenche a tabela com os dados obtidos
        DefaultTableModel model = new DefaultTableModel(dados, colunas);
        tbEmpresa.setModel(model);
    }

     // Exibe os dados das empresas na tabela
    public void exibirDados() {
        try {
            EmpresaDAO empresaDAO = new EmpresaDAO();
            List<Empresa> resultados = empresaDAO.listar();
            preencherTabela(resultados);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar dados: " + ex.getMessage());
        }
    }

    // Construtor que inicializa a tela e exibe os dados automaticamente
    public TelaEmpresa() {
        initComponents();
        setTitle("Sistema de cadastro de Pagamento - SCP");
        exibirDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmpresa = new javax.swing.JTable();
        btnIncluir = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        btnTelaInicial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tela de Empresas"));

        tbEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Empresa", "CNPJ", "Banco", "Cód. Banco", "Tipo de Conta", "Agência", "Digito da Agência", "Conta", "Digito da Conta", "Chave Pix", "Nome do Recebedor", "CNPJ do Recebedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbEmpresa);

        btnIncluir.setBackground(new java.awt.Color(0, 51, 204));
        btnIncluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIncluir.setForeground(new java.awt.Color(255, 255, 255));
        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(0, 0, 0));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel1.setText("Pesquisar:");

        txtPesquisar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPesquisarCaretUpdate(evt);
            }
        });

        btnTelaInicial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTelaInicial.setText("Tela Inicial");
        btnTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaInicialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(btnTelaInicial)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir)
                    .addComponent(btnExcluir)
                    .addComponent(jLabel1)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTelaInicial)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Exclui uma empresa e seus dados bancários selecionados
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linhaSelecionada = tbEmpresa.getSelectedRow(); // Obtém a linha selecionada

        // Verifica se há uma linha selecionada
        if (linhaSelecionada != -1) { 
            Object valorEmpresaId = tbEmpresa.getValueAt(linhaSelecionada, 0);
            Object valorDadosBancariosId = tbEmpresa.getValueAt(linhaSelecionada, 0);

            if (valorEmpresaId != null && valorDadosBancariosId != null) {
                int empresaId = Integer.parseInt(valorEmpresaId.toString());
                int dadosBancariosId = Integer.parseInt(valorDadosBancariosId.toString());

                // Confirmação do usuário
                int confirmacao = JOptionPane.showConfirmDialog(
                        this, "Tem certeza que deseja excluir esta empresa e seus dados bancários?",
                        "Confirmação", JOptionPane.YES_NO_OPTION);

                if (confirmacao == JOptionPane.YES_OPTION) {
                    EmpresaDAO empresaDAO = new EmpresaDAO();
                    DadosBancarioDAO bancarioDAO = new DadosBancarioDAO();

                    // Excluir dados bancários pelo ID
                    bancarioDAO.excluirDadosBancarios(dadosBancariosId);

                    // Excluir a empresa pelo ID
                    empresaDAO.excluirEmpresa(empresaId);

                    // Atualizar a tabela após a exclusão
                    exibirDados();
                }
            } else {
                JOptionPane.showMessageDialog(this, "O valor selecionado é nulo.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma empresa para excluir.");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    // Abre a tela de cadastro de empresas
    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        CadastroEmpresas cadastroEmpresas = new CadastroEmpresas();
        cadastroEmpresas.setVisible(true);
    }//GEN-LAST:event_btnIncluirActionPerformed

    // Volta para a tela inicial
    private void btnTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaInicialActionPerformed
        TelaInicial inicial = new TelaInicial();
        inicial.setVisible(true);
    }//GEN-LAST:event_btnTelaInicialActionPerformed

    // Método para buscar empresas a partir do nome digitado no campo de pesquisa
    private void txtPesquisarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPesquisarCaretUpdate

        String filtro = txtPesquisar.getText().trim();
        if (!filtro.isEmpty()) {
            try {
                EmpresaDAO empresaDAO = new EmpresaDAO();
                List<Empresa> empresasFiltradas = empresaDAO.listarEmpresa(filtro);

                if (empresasFiltradas.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Nenhuma empresa encontrada com esse nome.");
                } else {
                    preencherTabela(empresasFiltradas);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao buscar empresa: " + ex.getMessage());
            }
        } else {
            exibirDados();
        }
    }//GEN-LAST:event_txtPesquisarCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnTelaInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbEmpresa;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
